---
- hosts: gitlab
  become: yes
  tasks:
    - shell: >-
        cat /etc/gitlab/gitlab.rb | sed -rn "s/^external_url 'https:\/\/(.*)'$/\1/p"
      changed_when: false
      register:
        discovered_gitlab_host

    - set_fact:
        gitlab_host: "{{ discovered_gitlab_host.stdout }}"


- hosts: gitlab-runners
  become: yes

  pre_tasks:
    - script: scripts/ansible-seed-debian.sh
      register: ansible_seed
      changed_when: ansible_seed.rc == 0
      failed_when: ansible_seed.rc != 0 and ansible_seed.rc != 42

  roles:
    - debian-base
    - role: gitlab-runner
      gitlab_runner_name: "bolt"
      gitlab_runner_tags:
        - "std"
      gitlab_runner_user: "runner"
      gitlab_runner_pass: "Bidibul42#"
      gitlab_runner_master: "{{ hostvars[groups['gitlab-ci'][0]]['gitlab_host'] }}"
      gitlab_runner_master_crt: "{{ inventory_dir }}/secrets/ca.crt"
      gitlab_runner_register_url: "https://{{ hostvars[groups['gitlab-ci'][0]]['gitlab_host'] }}/ci"
      gitlab_runner_register_token: "D1u-e2RdpazZMh6E57Cy"


