---
- name: Retrieving hostname of gitlab to get certs right
  hosts: gitlab
  become: yes
  tasks:
    - shell: >-
        cat /etc/gitlab/gitlab.rb | sed -rn "s/^external_url 'https:\/\/(.*)'$/\1/p"
      changed_when: false
      register:
        discovered_gitlab_host

    - set_fact:
        gitlab_host: "{{ discovered_gitlab_host.stdout }}"


- hosts: gitlab-runners
  become: yes

  pre_tasks:
    - script: scripts/ansible-seed-debian.sh
      register: ansible_seed
      changed_when: ansible_seed.rc == 0
      failed_when: ansible_seed.rc != 0 and ansible_seed.rc != 42

    - set_fact:
        gitlab_runner_name: "{{ gitlab_runner_user }}"
        gitlab_runner_master: "{{ hostvars[groups['gitlab'][0]]['gitlab_host'] }}"
        gitlab_runner_master_crt: "{{ inventory_dir }}/secrets/ca.crt"
        gitlab_runner_register_url: "https://{{ hostvars[groups['gitlab'][0]]['gitlab_host'] }}/ci"

  roles:
    - debian-base
    - gitlab-runner
