---
- name: Adding Docker apt key
  apt_key:
    keyserver: "hkp://p80.pool.sks-keyservers.net:80"
    id: "58118E89F3A912897C070ADBF76221572C52609D"
    state: present

- name: Adding Docker apt repository
  apt_repository:
    repo: "deb https://apt.dockerproject.org/repo debian-jessie main"
    state: present
    update_cache: yes

- name: Installing Docker engine
  apt:
    name: "docker-engine"
    state: present

- name: Enabling Docker service
  service:
    name: "docker"
    state: started
    enabled: yes

- name: Installing docker-py to enable ansible docker modules
  pip:
    name: "docker-py"
    state: present

- name: Create docker trusted certs directory
  file:
    path: "/etc/docker/certs.d/{{ gitlab_runner_master }}"
    state: directory

- name: Uploading gitlab crt to docker trusted certs
  copy:
    src: "{{ gitlab_runner_master_crt }}"
    dest: "/etc/docker/certs.d/{{ gitlab_runner_master }}/ca.crt"
  notify: update ca certs

- name: Uploading gitlab crt to shared trusted certs
  copy:
    src: "{{ gitlab_runner_master_crt }}"
    dest: "/usr/local/share/ca-certificates/{{ gitlab_runner_master }}.crt"
  notify: update ca certs
